name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.12]
        poetry-version: [2.1.2]
        vcpgk-version: [2025.04.09]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install Poetry
        run: |
          pip install poetry==${{ matrix.poetry-version }}
      - name: Poetry install
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root
      - name: Set up vcpkg
        id: vcpkg
        run: |
          git clone --branch ${{ matrix.vcpgk-version }} --single-branch https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh --disableMetrics
          ./vcpkg integrate install
          echo "VCPKG_ROOT=$(pwd)" >> "$GITHUB_OUTPUT"
      - name: Install clangd
        run: |
          sudo apt-get install -y clangd-18
          sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-18 100
      - name: Install make
        run: |
          sudo apt-get install -y make
      - name: Clone xtensor-python
        run: |
          git clone https://github.com/xtensor-stack/xtensor-python.git ${{ github.workspace }}/python/extern/xtensor-python
      - name: Cmake
        env:
          VCPKG_ROOT: ${{ steps.vcpkg.outputs.vcpkg_root }}
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
                -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF \
                -DCMAKE_C_COMPILER=/usr/bin/clang \
                -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
                -DCMAKE_CXX_STANDARD=20 \
                -DCMAKE_CXX_STANDARD_REQUIRED=ON \
                -DCMAKE_CXX_EXTENSIONS=OFF \
                -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install/ \
                -DPython_EXECUTABLE=$pythonLocation \
                -S${{ github.workspace }} \
                -B${{ github.workspace }}/build \
                -G Ninja
